function Q = computeQ_givenEllParam(a, b, theta)
    Q = [a.^2.*cosd(theta).^2+b.^2.*sind(theta).^2, ...
        (a.^2 - b.^2).*sind(theta).*cosd(theta);...
        (a.^2 - b.^2).*sind(theta).*cosd(theta),...
        a.^2.*sind(theta).^2+b.^2.*cosd(theta).^2];
end